### PR TITLE
Support Magento 2.4.6 and 2.4.7 with PHP 8.2 and 8.3

### PR DESCRIPTION
**Pull request by evs-xsarus**

### CODE REVIEW

**Comment by evs-xsarus** [comment]
@imichaelv do you have time to look at the open MRs?

**Comment by jellesiderius** [comment]
Can someone look into this? Would be nice.

**Review by seleno-stefan — APPROVED** [review]

**Comment by evs-xsarus** [comment]
@seleno-stefan could you also create a release with this commit?

**Comment by seleno-stefan** [comment]
Release is created now. See https://github.com/forwarder/belco-magento2/releases/tag/v0.4.4

**Pull request merged**
